### ISSUE TITLE
Followup on machine readable output (PR#1196)

### ISSUE THREAD

**Issue by kadel** [openshift/odo#1263]
followup to: https://github.com/redhat-developer/odo/issues/1062
parent: https://github.com/redhat-developer/odo/issues/784

PR for Machine readable output (https://github.com/redhat-developer/odo/pull/1196) was put together quickly and it is missing a lot and also it needs a lot of cleanups:

   - [x] a function like `component.List` should return new structures (in this example `ComponentList`) etc.., only printing logic should be inside `cmd` - Issue https://github.com/redhat-developer/odo/issues/1270
-  [x] every command should have the possibility to specify `-o json` (maybe it could be global flag?)
   -  [ ] create commands -  for example `odo component create -o json` the output of the command should be the object created by the command, in this example the command should return newly created component (https://github.com/redhat-developer/odo/issues/1377)
    - [ ] delete  - don't have to return anything in case of `-o json` we just have to make sure that proper return code is returned (0 on successful deletion)  (https://github.com/redhat-developer/odo/issues/1383)
    - [ ] push and watch - don't know what to do with it right now
    - [ ] link  - probably the same as delete
    - [ ] service related commands (missing struct for service)
    - [ ] how is a link going to be represented? (a field in ComponentSpec? something else?)
 - [ ] missing fields and other enhancements for machine readable structs - Issue https://github.com/redhat-developer/odo/issues/1271
We don't need to implement our own printing logic, we can use https://github.com/kubernetes/cli-runtime ([printers](https://github.com/kubernetes/cli-runtime/tree/master/pkg/genericclioptions/printers))
- [ ] Add completion handler for output flag https://github.com/redhat-developer/odo/issues/1273
Requirements:
   - use cli-runtime where possible
   - functions are returning new types (returning objects are not created inside `cmd`)
   - every command can be run with `-o json`
   - every command with `-o json`  has covered by a test

**Comment by metacosm** [comment]
@kadel so is the idea to merge #1196 and then work on this to clean things up?

**Comment by kadel** [comment]
> @kadel so is the idea to merge #1196 and then work on this to clean things up?

yes. The reason is to get quick feedback, and also to prevent big PRs

**Comment by girishramnani** [comment]
> * inside `cmd`
- this would mean the Complete-Validate and Run functions of a cobra.Command? @kadel

**Comment by surajnarwade** [comment]
>  a function like component.List should return new structures (in this example ComponentList) etc.., only printing logic should be inside cmd - Issue #1270

That means, cmd should do print/marshaling 


>  every command should have the possibility to specify -o json (maybe it could be global flag?)

`-o` is not a global flag in kube/oc, Also  for commands like `odo push` , `-o` makes no sense, I think.

>  how is a link going to be represented? (a field in ComponentSpec? something else?)

Maybe in status field

**Comment by surajnarwade** [comment]
me and mrinal discussed few stuffs around this issue:

initial stage should be:

* Get rid of normal structs. for example, `Description`  for component, add all required fields to machine readable output and the following issue.

* refactor other functions to reuse machine readable structs, 
for example: for normal function uses `URL` struct and for list, use `URLList` struct
TODO:
- [ ] URL
- [ ] Storage
- [ ] Application
- [ ] Component
- [ ] Project 

* For deletion, `-o json` makes no sense, instead, we should give status code gracefully.

**Comment by kadel** [comment]
> > a function like component.List should return new structures (in this example ComponentList) etc.., only printing logic should be inside cmd - Issue #1270
> 
> That means, cmd should do print/marshaling

yes, idealy using  kubernetes/cli-runtime



> 
> > every command should have the possibility to specify -o json (maybe it could be global flag?)
> 
> `-o` is not a global flag in kube/oc, Also for commands like `odo push` , `-o` makes no sense, I think.

Why not? For someone who is writing a tool that uses odo, it will be much easier to expect that `-o` is always there, even `odo push` can also return output in a structured format.

But we can figure out this later, I've added it here to make sure that we don't forget about this.


> 
> > how is a link going to be represented? (a field in ComponentSpec? something else?)
> 
> Maybe in status field

+1

**Comment by surajnarwade** [comment]
Closing since we have recent issues to track this
