### ISSUE TITLE
odo support for Quarkus

### ISSUE THREAD

**Issue by sspeiche** [openshift/odo#1444]
As a Java Function and Microservice developer, I'd like to leverage the latest in Java technology with OpenShift using a streamlined CLI tool with Quarkus.

## Which functionality do you think we should update/improve?
Provide 1st class support for applications based on Quarkus work. This includes validating there is a S2I image that works with push/watch. Also to make sure that hot-reload capabilities can be leveraged as well.

Quarkus tracking issue https://github.com/quarkusio/quarkus/issues/1390

## Acceptance Criteria from the linked User Story

 * [x]  odo workflow should work well with quarkus apps
   `odo create` `odo push`  `odo delete` `odo url create`, accessing application from given url.
 * [x]  `odo catalog list components` should list down quarkus as supported app
 * [x]   Example Devfile needs to be added in devfile registry.
   https://github.com/elsony/devfile-registry/tree/master/devfiles
   https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/quarkus/devfile.yaml
 * [x]  Integration tests for quarkus support in odo
 * [x]  Update the relevant Documents

**Comment by geoand** [comment]
I can work on this on the `odo` side of things. But I would like to from @kadel and @jorgemoralespou if we think that a new s2i image will be needed or if we can somehow fit the Quarkus workflow into the existing java s2i image

**Comment by kadel** [comment]
> I can work on this on the `odo` side of things. But I would like to from @kadel and @jorgemoralespou if we think that a new s2i image will be needed or if we can somehow fit the Quarkus workflow into the existing java s2i image

I don't know enough about Quarkus to answer this :-(

**Comment by geoand** [comment]
No problem, we should have a quick chat about this :)

**Comment by jorgemoralespou** [comment]
@kadel @geoand the regular java s2i should work, but what does not work is `odo`.

Quarkus does run with the following command in dev mode (for hot reload) `mvn quarkus:dev`. The idea of quarkus dev mode is also that the files will be used from where they are, so there need not to be moved to a deployment directory after assemble, which needs to be `mvn compile` and this only need to be executed on first deployment.

Easiest way would be to:
1) have an empty assemble
2) use a run with `mvn compile quarkus:dev`
These can be initially added to the source code repository in an `.s2i/bin/` folder. We would need to make sure that odo does not do things when pushing the files to the container, as it would add a time penalty with the backup/restore steps done in the container.

This is an example of how the `odo image scripts` would benefit the process of working with specific languages/images. Sadly that definition is stalled.  @kadel I would involve @geoand @metacosm on helping push this forward.

**Comment by geoand** [comment]
@jorgemoralespou @kadel @metacosm I think we should schedule a call to work out how we can make this happen

**Comment by jorgemoralespou** [comment]
@geoand I'm traveling to Singapore this week, so on an off (more off than on). I hope @kadel can discuss this with you guys.

**Comment by geoand** [comment]
OK @jorgemoralespou :)

**Comment by kadel** [comment]
> @kadel @geoand the regular java s2i should work, but what does not work is `odo`.

Not sure what you mean :-(


> 
> Quarkus does run with the following command in dev mode (for hot reload) `mvn quarkus:dev`. The idea of quarkus dev mode is also that the files will be used from where they are, so there need not to be moved to a deployment directory after assemble, which needs to be `mvn compile` and this only need to be executed on first deployment.
> 
> Easiest way would be to:
> 
> 1. have an empty assemble
> 2. use a run with `mvn compile quarkus:dev`

This should be handled inside the image

>    These can be initially added to the source code repository in an `.s2i/bin/` folder. We would need to make sure that odo does not do things when pushing the files to the container, as it would add a time penalty with the backup/restore steps done in the container.
> 
> This is an example of how the `odo image scripts` would benefit the process of working with specific languages/images. Sadly that definition is stalled. @kadel I would involve @geoand @metacosm on helping push this forward.

**Comment by jorgemoralespou** [comment]
@kadel, what I mean is that since quarkus does hot reload of files in their current location, how odo interacts with the images calling assemble_and_run will not provide a nice experience. The image, the openjdk images, can be used, with some tweaks, as I mentioned the location of the /opt/app-root/src and /deployments should be the same, as files should not need to be moved. Else the experience that Quarkus provides where it reloads the runtime automatically on changes (or only changes the files/classes needed) would not be perceived and the experience would be bad.

This is why, we need to be able to instruct the images what to do in certain scenarios, and yes, while we could create a dedicated Quarkus s2i, which would simplify things a lot, we can probably still probably make it work on the OpenJDK image without too much hassle.

**Comment by cdrage** [comment]
As we reach GA, should this be marked at 1.0 GA for some basic form of documentation as to whether or not we support quarkus?

@kadel

**Comment by magick93** [comment]
Please do, odo please support quarkus!

**Comment by girishramnani** [comment]
This issue is blocked on dev file support https://github.com/openshift/odo/issues/2470
as it uses dev file to provide support for quarkus

**Comment by adisky** [comment]
Rough outline:
Quarkus Support

Dependent Devfile PR's
Devfile exec PR needs to merged
Devfile delete PR needs to be merged

Quarkus dev file needs to be modified for odo
https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/quarkus/devfile.yaml

Manual Local Testing of quarkus deployment with modified devfile
Integrations tests for quarkus in odo

**Comment by cdrage** [comment]
@adisky We should have multiple issues as well as an outline of what needs to be done.

- Criteria that needs to be completed
- List of PR's / Issues that need to be merged in before adding Quarkus Support
- Maybe even a proposal document
- Changes to be made upstream (https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/quarkus/devfile.yaml)

**Comment by adisky** [comment]
> @adisky We should have multiple issues as well as an outline of what needs to be done.
> 
> * Criteria that needs to be completed
> * List of PR's / Issues that need to be merged in before adding Quarkus Support
> * Maybe even a proposal document
> * Changes to be made upstream (https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/quarkus/devfile.yaml)

@cdrage for the format, I would convert this into user story, so that it will cover all aspects.

**Comment by girishramnani** [comment]
Progress so far 

> ## Acceptance Criteria
> * [x]  odo workflow should work well with quarkus apps
>   `odo create` `odo push`  `odo delete` `odo url create`, accessing application from given url.
> * [x]  `odo catalog list components` should list down quarkus as supported app
> * [x]   Example Devfile needs to be added in devfile registry.
>   https://github.com/elsony/devfile-registry/tree/master/devfiles
>   https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/quarkus/devfile.yaml
> * [ ]  Integration tests for quarkus support in odo
> * [ ]  Update the relevant Documents

**Comment by girishramnani** [comment]
as of now - we dont need special integration tests for quarkus as we have tests in the devfile registry for these

**Comment by girishramnani** [comment]
also all the relevant documents have been updated.
