### ISSUE TITLE
UC 8: As a developer, I want to list components (DB, datagrid, storage, …) in my application

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/odo#153]
As a developer, I want to be able to list all components that my application (database, datagrid, storage, etc.) has.

```
$ ocd list [--app=]  [--type=database|java|whatever] (defaults to components that I have deployed)
You have deployed:
myeap using the eap:6.4 component
postgres using the postgresql:8.4 persistent component
```

Tasks:

- [x]  [ocd list should list components in current application](https://github.com/redhat-developer/ocdev/issues/191)

- [x] [ocd list should list components in the provided application](https://github.com/redhat-developer/ocdev/issues/192)

- [ ] [ocd list should allow to filter components by type](https://github.com/redhat-developer/ocdev/issues/193)

**Comment by slemeur** [comment]
Foundations are there.
We should decompose this epic into sub-issues and add the sub-issues into the milestone-mvp.

@kadel @containscafeine : Could you please create the sub-issues for that particular use case.

**Comment by surajnarwade** [comment]
Closing this as most of the things are already covered and remaining can be tracked here: https://github.com/openshift/odo/issues/926
