### ISSUE TITLE
UC 11: As a developer, I want to delete specific components from my application

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/odo#156]
As a developer, I want to be able to delete components with a single command.

```
$ ocd delete [myfrontend]
Do you really want to delete myfrontend in application <name> (y/n)?
Component myfrontend will be deleted.
This component was externally exposed, and the URL will be removed
Delete a binding to other service
Other non-essential stuff as needed
(if there is storage) Should we delete the associated storage (y/n)?
```

Tasks (create new issues if deferring some work):
- [x] #201 If name of the component is not specified, then delete current component.
- [x] If name of the component is specified, then delete specified component.
- [x] #200 Delete should always ask for confirmation.
- [x] Delete should show what other things get deleted as part the action
- [x] If cascading delete includes storage, should again ask for removal confirmation

**Comment by cdrage** [comment]
3/5 completed. I do agree with regards to the last two parts. 

We should:

 - [ ] Have debugging messages indicating what is being deleted
 - [ ] If storage will be deleted, prompt for confirmation.

**Comment by jorgemoralespou** [comment]
It should allow providing `--force` and/or `-f` flag for skip confirmation. This needs to be true in each subtask.

**Comment by surajnarwade** [comment]
@jorgemoralespou we have a flag `-f` to skip confirmation in all `deletion` tasks

**Comment by jorgemoralespou** [comment]
Cool, didn't notice it.

**Comment by kadel** [comment]
/close 
all implemented
