### ISSUE TITLE
UC 12: As a developer, I want to delete an application and all its components

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/odo#157]
As a developer, I want to be able to delete my entire application with a single command.

```
$ ocd app delete [--app=name]
Current application XYZ will be deleted.
Component ABC will be deleted:
This component was externally exposed, and the URL will be removed
This component used storage and it will be removed
Component DB1 will be deleted:
This component was externally exposed, and the URL will be removed
This component used storage and it will be removed
Component DB2 will be deleted:
This component was externally exposed, and the URL will be removed
This component used storage and it will be removed

Do you really want to delete application <name> (y/n)?
```

Tasks (create new issues if deferring some work):
- [x] #202 If name of the app is not specified, then delete current app.
- [x] If name of the app is specified, then delete specified app.
- [x] #203 Delete should always ask for confirmation.
- [x] #204 Delete should show what other things get deleted as part the action
- [x] If cascading delete includes storage, should again ask for removal confirmation

**Comment by kadel** [comment]
Decompose this to subtasks. 
This is partially implemented. Asking for confirmation is missing.

**Comment by cdrage** [comment]
All has been completed with the exception of:

- [ ]  If cascading delete includes storage, should again ask for removal confirmation


(correct me if I'm wrong)

**Comment by jorgemoralespou** [comment]
There should be a `--force` and `-f` flag so that deletion doesn't ask for confirmation when the flag is provided. This should happen in each of the previous subtasks.

**Comment by surajnarwade** [comment]
@jorgemoralespou @cdrage , we already have `--force`, `-f` for forcefully deletion,  we just need to support `if cascading delete includes storage, should again ask for removal confirmation`

**Comment by kadel** [comment]
all implemented
/close
