### ISSUE TITLE
TODO for adoc to markdown conversion for the site

### ISSUE THREAD

**Issue by cdrage** [openshift/odo#1578]
[kind/Documentation]

List of TODO's:

- [ ] Have TravisCI build and then push to gh_pages (pure html not jekyll)
- [ ] Move relevant site information to the `master` branch so users may build the site themselves / more central location
- [ ] Fix synchronization script for adoc building
- [ ] Add jekyll-asciidoc plugin

Let me know what's missing @rkratky

**Comment by rkratky** [comment]
@cdrage, it will also be necessary to adjust Jekyll config a bit. At minimum, the following will need to be added:
```
asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    imagesdir: <img_location>
    page-liquid: ''
    source-highlighter: rouge
    icons: font
```
On the other hand, the Gemfile could probably be a bit leaner. I think the following should suffice:
```
source "https://rubygems.org"

group :jekyll_plugins do
  gem 'jekyll-asciidoc'
end
```
Note: I guess it would be worth it to build our own image with Jekyll to build the site (instead of using the generic `jekyll/jekyll`). I tried to base it on an Alpine Ruby image (`ruby:alpine`), and it came out half the size than when starting with even `jekyll/minimal`. The following Dockerfile should be enough:
```
FROM ruby:alpine
COPY Gemfile /tmp/
RUN apk add --no-cache --virtual build-dependencies build-base \
    && cd /tmp && bundle install \
    && apk del build-dependencies build-base
CMD jekyll help
```

**Comment by Preeticp** [comment]
@kadel, @cdrage if I am not mistaken this was completed and can be closed. If not, is there anything we can help with?

**Comment by cdrage** [comment]
@Preeticp Just keeping this open until I fix the sync script which I haven't gotten around to doing yet. Everything else has been completed however!

**Comment by cdrage** [comment]
Actually, I'm going to close this in favour of:
https://github.com/openshift/odo/issues/1679
