### ISSUE TITLE
UC 19: As a developer, I want to have sane defaults for application name and component name.

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/odo#164]
As a developer, I want to have sane defaults for application name and component name so that if I’m working with just one application in my current project, or just one component, I’m not required to provide the name for it, but it will be auto-generated under the cover.
The name needs to also contain a randomized value in it, so that a directory can be reused for multiple applications-components.

```
$ cd my-code-frontend
$ ocd create httpd (app=app, comp=httpd)
------------------------
$ cd my-code-frontend
$ ocd create httpd (app=app, comp=httpd)
$ ocd create httpd (app=app)
You already have a httpd component.  Please specify a name for as you can not have two components with the same name.  Please rerun and specify a name which the following syntax:
   $ ocd create httpd myname
   $ ocd create httpd myname --git=urltorepo
```

Tasks:
- [x] #216 Define random generated pattern to use on default names (can be totally random, or within a list of values, like Docker)
- [x] #218 Use "app (and a random generated pattern)" name as application name if not specified (e.g. app-xy1h)
- [x] #217 Use "component type" as component name if not specified. If wildfly or httpd or python or mysqldb are the components, use those as the component name.

**Comment by kadel** [comment]
this needs to be decomposed. Parts of this might not be in MVP

**Comment by surajnarwade** [comment]
Closing this as all of the concerns from this issue are addressed :smile:  :tada: 
@jorgemoralespou , feel free to reopen if there's anything remaining
