### ISSUE TITLE
UC 26: As a Developer, I want to be able to link/unlink two components together

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/odo#171]
As a Developer, I want to be able to link/unlink two components together such as a component get injected the credentials to use a different component (the linked one)

```
$ ocd create mongodb
$ ocd create tomcat
$ ocd link mongodb [--component=tomcat]
Expected output:
mongodb has been linked to tomcat
Connection information for mongodb has been injected
--------------
$ ocd unlink mongodb [--component=tomcat]
```

Tasks (add issues if tasks are deferred):
- [x] Link (defaults to current active component) #342
- [x] Link specifying target component #342
- [ ] Link specifying additional parameters (name of secret, ENVs to use, ...)
- [x] Unlink #929

**Comment by kadel** [comment]
It would be nice to at least hack this in for MVP.
We need to decompose this.

**Comment by containscafeine** [comment]
Linking has been implemented in #342

**Comment by cdrage** [comment]
We've implemented this in #342 closing.

**Comment by jorgemoralespou** [comment]
Is unlink implemented?

**Comment by cdrage** [comment]
@jorgemoralespou Woops. No it's not, missed that completely. Leaving this open!

**Comment by mik-dass** [comment]
@cdrage @kadel I would like to pick this up and implement the rest

**Comment by mik-dass** [comment]
@jorgemoralespou @kadel I think we need to fix `odo link` as it was designed and implemented for components with only one service port. But since now we support components with multiple ports in service, I think we need to redesign it. WDYT?

**Comment by jorgemoralespou** [comment]
@mik-dass there's probably more things that will need to be done, but we should also talk to the servicecatalog guys as this is a functionality that is somehow also going to be implemented from the openshift side. cc/ @sspeiche

**Comment by jorgemoralespou** [comment]
This service linking was done for the Summit demo, or with those requirements. We need to work very much this use case and know what it's coming from OpenShift side.

**Comment by kadel** [comment]
> @jorgemoralespou @kadel I think we need to fix `odo link` as it was designed and implemented for components with only one service port in #342 . But since now we support components with multiple ports in service, I think we need to redesign it. WDYT?

`odo link` was implemented just as a proof of concept for the Summit demo. 
We have to put a lot more work into it and it will require complete redesign as this commands should also work with services created from the service catalog.

**Comment by mik-dass** [comment]
@sspeiche Currently `odo link` shoehorns in the env vars in deploy config.

**Comment by geoand** [comment]
#856 makes link work by injecting a secret into the DC

**Comment by kadel** [comment]
only missing piece from this is linking with parameters
that will be addressed later as a separate issue
/close
