### ISSUE TITLE
UC 27: As a developer, I want to be able to manage URL for a component in an easy way

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/odo#172]
As a developer, I want to be able to expose a component to the outside world in an easy way, only requiring the common minimal information (hostname, path, secure) 

Routes scenarios:
- Create a route
- Modify route
- Delete Route

```
$ ocd url create [name] [--hostname] [--path] [--secure] [--component]
$ ocd url update [name]  [--hostname] [--path]  [--component] 
$ ocd url delete [name]  [--component]  [--secure]
-------------
$ ocd url create
$ ocd url create --secure

-------------
$ ocd url delete 
$ ocd url delete --secure
```

__*NOTE:*__ When name is not specified, it defaults to the name of the current component (as in all the other commands). When a non-secure route is being created, the name is defaulted to “<name>” vs. when a secure route is being created and a name is not explicitly stated, it is defaulted to “<name>-secure”.

Eventually we would probably want to have commands or support for:
- A/B?
- Blue/Green?

Tasks (create issues if tasks are deferred):
- [x] Create a route
  - [x] To active component
    - [x] With default values
    - [ ] With user provided values 
  - [x] To specified component
    - [x] With default values
    - [ ] With user provided values 
- [ ] Create a secure route
  - [ ] To active component
    - [ ] With default values
    - [ ] With user provided values 
  - [ ] To specified component
    - [ ] With default values
    - [ ] With user provided values 
- [ ] Modify route
  - [ ] To active component
    - [ ] With default values
    - [ ] With user provided values 
  - [ ] To specified component
    - [ ] With default values
    - [ ] With user provided values 
- [ ] Modify secure route
  - [ ] To active component
    - [ ] With default values
    - [ ] With user provided values 
  - [ ] To specified component
    - [ ] With default values
    - [ ] With user provided values 
- [x] Delete Route
  - [x] To active component
  - [x] To specified component

Subtasks:
 - #65 
 - #231

**Comment by kadel** [comment]
it needs to be decomposed to subtasks. 
At least `create` needs to be there for MVP

**Comment by kadel** [comment]
url create, delete and  list added in  PR #252. This should enough for MVP

**Comment by surajnarwade** [comment]
From this issue, we almost have everything except `--secure` flag

**Comment by kadel** [comment]
secure will be addressed later in a separte issue based on the need 
/close
