### ISSUE TITLE
List & Provision Services from the in-cluster installed operators (Dev Catalog)

### ISSUE THREAD

**Issue by sbose78** [openshift/odo#2161]
[kind/Enhancement]

## Which functionality do you think we should update/improve?
`odo catalog list services`

## Why is this needed? 
Support in-cluster Operator Catalog as the primary way to look-up and provision services, as an alternative to Service Catalog.

It should behave as demonstrated here https://asciinema.org/a/261224  

## Challenges
1. By default, none of the operators in the OLM Catalog are installed. `odo catalog list services` could potentially be empty - unless we silently install the operator if not installed before usage.
2. Creating a service would entail creating a CR that would be managed by the OLM operator. There's no good way to know which is the primary CR associated with a Database operator for example.

## Implementation Approaches & Existing Work
* Appears no existing CLI tools exist
* (from Evan, OLM lead) 

> Mostly this will be vendoring in OLM's apis. We are looking to place that in `operator-framework/api`, but for now they're in `operator-framework/operator-lifecycle-manager`. The dynamic forms in console are driven by the metadata available on the ClusterServiceVersion and the schemas of the CRDs owned by the operators.

* (from Rob S, OLM PM) 
Some brainstorming...
> 1. What type of service do you want to create?
> - api
> - database
> - ...
> 2. What type of database?
> [...list of CR types from OLM with that category...]
> 
> [...grab descriptions from CSV...]
> 3. Enter required values
> [...pull these from the schema with default values...]
> 4. Provide a name for your database
> foobar
> 5. Wait for the service to deploy?
> Yes
> 6. Creating the following resources:
> [...match resource tab from Console...]

## User Stories

- [ ] Validating the cluster for operator and service catalog capability and odo service list https://github.com/openshift/odo/issues/2461
- [ ] odo service describe for operators + services https://github.com/openshift/odo/issues/2615
- [ ] Instantiating operators using CRDs https://github.com/openshift/odo/issues/2462
- [x] status command for operators https://github.com/openshift/odo/issues/2479
- [ ] Use the service binding operator to link operator and a component https://github.com/openshift/odo/issues/2463
- [x] enhance the odo service delete command to allow deletion of operators https://github.com/openshift/odo/issues/2792

**Comment by kadel** [comment]
What is the best way to list installed operators on the cluster?

**Comment by sbose78** [comment]
oc get csvs

**Comment by tmds** [comment]
Is `odo service` unusable until this gets resolved?

**Comment by kadel** [comment]
> Is `odo service` unusable until this gets resolved?
> 
> I've enabled the service catalog (following https://docs.openshift.com/container-platform/4.2/applications/service_brokers/installing-service-catalog.html).
> There are no services:
> 
> ```
> > $ odo catalog list services
>  ✗  no deployable services found
> ```

Is odo service unusable until this gets resolved?
No, It should be useable, as long as you have a service catalog deployed on the cluster.

Can you try `oc get clusterserviceclasses` to validate that the ServiceCatalog is running on your cluster?

**Comment by tmds** [comment]
> oc get clusterserviceclasses
```
$ oc get clusterserviceclasses
No resources found in default namespace.
```

**Comment by girishramnani** [comment]
Broken this issue down into following issues in order -
- https://github.com/openshift/odo/issues/2461
- https://github.com/openshift/odo/issues/2462
- https://github.com/openshift/odo/issues/2463
- https://github.com/openshift/odo/issues/2464

**Comment by girishramnani** [comment]
I feel there can be 2-3 more issues related to
-  parsing the validation spec to help the user
- use the metadata provided in `ClusterServiceVersion`
- confirming ansible and helm based operators also work

**Comment by prietyc123** [comment]
There is no point in keeping this issue for milestone 1.2, Hence moving it to milestone 1.3

**Comment by girishramnani** [comment]
We have a more updated Epic for this and hence removing this from the milestone in the interest of https://github.com/openshift/odo/issues/2613
