### ISSUE TITLE
Invalid URL annotation generated with binary component

### ISSUE THREAD

**Issue by jeffmaury** [openshift/odo#2175]
[kind/bug]

## What versions of software are you using?
- Operating System: Win10
- Output of `odo version`:

```
odo v1.0.0-beta5 (4d1d5071)     
                                
Server: https://172.18.84.5:8443
Kubernetes: v1.11.0+d4cacc0
```     

## How did you run odo exactly?

`odo create java:8 bincomp --binary target\springboot-rest2-1.0.0-SNAPSHOT.jar --project bin --app binapp`

## Actual behavior

The generated annotation is:

`app.openshift.io/vcs-uri: 'file:///target/springboot-rest2-1.0.0-SNAPSHOT.jar'`
## Expected behavior

Should be:

`app.openshift.io/vcs-uri: 'file:target/springboot-rest2-1.0.0-SNAPSHOT.jar'`

That would allow tooling (VSCode, IntelliJ) to use this annotation to import a component from the deployment.

**Comment by amitkrout** [comment]
```
The generated annotation is:
app.openshift.io/vcs-uri: 'file:///target/springboot-rest2-1.0.0-SNAPSHOT.jar'
```

@jeffmaury Where/how you got this annotation ?

**Comment by amitkrout** [comment]
<img width="1157" alt="Screen Shot 2019-09-25 at 2 12 56 PM" src="https://user-images.githubusercontent.com/19851115/65584847-2aa8a400-df9f-11e9-8359-4251450513bf.png">

Got it, It just follow the local path protocol of ```file:///``` on windows platform because the binary source being used is a local one.

**Comment by girishramnani** [comment]
@jeffmaury do you mean `file://` vs `file:///` because the later means its absolute path?

**Comment by jeffmaury** [comment]
I mean no / at all because it's a relative URL

**Comment by veillard** [comment]
ACK, it all depends on the context of the relative reference. if it's in a generated file and assuming the resource being pointed at is in the target subdirectory of where that file is placed then
     target/springboot-rest2-1.0.0-SNAPSHOT.jar

but it really depends on the context of where that file containing that URI reference is located  
See Section 4.1 of rfc 3986
https://www.ietf.org/rfc/rfc3986.txt

Problems: relative references are not defined for the file:// scheme , sucks isn't it :-)
the common usage is to convert file path with \ to / on Windows, try to avoid drive prefix as this finishes to screw things up !

**Comment by veillard** [comment]
Using libxml2 URI test binary assuming the reference is contained in file:///home/veillard/test.yaml

thinkpad:~/XML -> ./testURI --base file:///home/veillard/test.yaml target/springboot-rest2-1.0.0-SNAPSHOT.jar
file:///home/veillard/target/springboot-rest2-1.0.0-SNAPSHOT.jar
thinkpad:~/XML -> ./testURI --base file:///home/veillard/test.yaml file:///target/springboot-rest2-1.0.0-SNAPSHOT.jar
file:///target/springboot-rest2-1.0.0-SNAPSHOT.jar
thinkpad:~/XML -> ./testURI --base file:///home/veillard/test.yaml file://target/springboot-rest2-1.0.0-SNAPSHOT.jar
file://target/springboot-rest2-1.0.0-SNAPSHOT.jar
thinkpad:~/XML -> 

Daniel

**Comment by mik-dass** [comment]
@kadel @jeffmaury @girishramnani Should this issue also include the local components?

**Comment by kadel** [comment]
@mik-dass It would be good to investigate if we even need this annotation for local and binary components. It doesn't make much sense to store a path that is on local system on the cluster. odo should read this path from `.odo/config.yaml`.
For git component, it makes sense to store it in annotations as it can be useful for other tools like developer console.

## Tasks
- [ ] make sure that `app.openshift.io/vcs-uri` is not read by odo anywhere
- [ ] stop adding `app.openshift.io/vcs-uri` annotation to local and binary components
- [ ] use `app.openshift.io/vcs-uri` annotation only for git component (we should be already doing it)


@jeffmaury 
> That would allow tooling (VSCode, IntelliJ) to use this annotation to import a component from the deployment.

Do you really need this annotation for local components? The information in this annotation doesn't provide enough information to do import no?
What is the use-case for importing  a component from the deployment?

**Comment by mik-dass** [comment]
> @mik-dass It would be good to investigate if we even need this annotation for local and binary components. It doesn't make much sense to store a path that is on the local system on the cluster. odo should read this path from .odo/config.yaml.
For git component, it makes sense to store it in annotations as it can be useful for other tools like developer console.

After some searching I found that the annotations `app.openshift.io/vcs-uri` is mostly used in testing, storing and displaying the path to the user. With some modification, I guess we can make the display tasks to use the local config and use this only for git components as the path is anyways relative.
