### ISSUE TITLE
Implement devfile push

### ISSUE THREAD

**Issue by rajivnathan** [openshift/odo#2470]
Implement devfile push in accordance with the implementation plan from #2290 

- [x] Devfile parsing (https://github.com/openshift/odo/issues/2477)
- [x] Create kclient (https://github.com/openshift/odo/issues/2436)
- [x] Implement Devfile Deployment support (https://github.com/openshift/odo/issues/2471)
- [x] Component sync support (https://github.com/openshift/odo/issues/2473)
- [x] Execute commands on containers within fat pod (https://github.com/openshift/odo/issues/2654)
- [x] Implement Devfile volume support (https://github.com/openshift/odo/issues/2472)
- [x] Create Service for endpoint entry in devfile (https://github.com/openshift/odo/issues/2622)

**Comment by mohammedzee1000** [comment]
For reference, please use feature wh/e you mean enhancement as well

**Comment by kadel** [comment]
> * [ ]  Implement Devfile volume support (#2472)

I would consider this for later stages.  odo and device can be useful and cover most of the use cases without this.

**Comment by GrooveCS** [comment]
**Queston** 
### VS Code Remote Development vs ODO (OpenShift Do)

How is ODO devfile different from Codes [ devcontainer.json](https://code.visualstudio.com/docs/remote/containers#_devcontainerjson-reference)?

**Comment by kadel** [comment]
> **Queston**
> 
> ### VS Code Remote Development vs ODO (OpenShift Do)
> How is ODO devfile different from Codes [ devcontainer.json](https://code.visualstudio.com/docs/remote/containers#_devcontainerjson-reference)?

@GrooveCS 
I don't know much about devcontainers.json, at first glance it looks similar. The biggest difference that I can see is that in devfilecontainers.json you can only specify containers (images or Dockerfile). Devfile can also include additional Kubernetes or OpenShift resources.

**Comment by j-c-berger** [comment]
@rajivnathan, hey Rajiv, ID is going through issues, and I was wondering if ID supported is needed for this issue. If so, let me know what you need, and I'm happy to help!

**Comment by elsony** [comment]
@j-c-berger This is the public repo for odo. Let's take offline on any of the Codewind project specific questions outside of this repo.

**Comment by kadel** [comment]
All the tasks linked in this issue are done

/close
