### ISSUE TITLE
MVP: Local support for devfile push

### ISSUE THREAD

**Issue by elsony** [openshift/odo#2576]
Add devfile push support to local (non-Kube) scenario.  The CLI usage pattern and the behaviour will be very similar to the corresponding devfile push scenario in Kubenetes.  

The MVP local scenario includes:

- [x] Add ability to switch context between local and kube (#2577)

- [x] Add lclient to handle local deployment functions similar to the kclient handling the Kube deployment functions (#2578)

- [x] odo create component support on local based on the same list of odo catalog from the Che devfile registry as the kube scenario, same devfile definition share between local and kube (#2579)

- [x] Odo push should work with local Docker containers (#2579)

- [x] Create docker volumes based off of volumes in devfile (#2849)

- [x] Devfile sync and exec support for local docker containers (#2717)

- [x] odo create url support on local to expose endpoint for application (#2580)

- [x] odo delete on local to clean up local resources (#2581)

- [x] odo application creation support - add ability to create application resource from stack (similar to Appsody init support) (#2582)
- [x] odo component init support - add ability to run init code to setup development environment for a given stack (similar to Appsody init support) (#2672)

MVP+ scenario:

- [ ] link services to application on local

- [x] add port reservation support to reserve port on local on create URL command (done as part of #2580)

Similar to the devfile support in Kube, all the local support will hiding behind the EXPERIMENTAL flag (#2536 ).

**Comment by kadel** [comment]
This will be a big task with a lot of specifics. I've created new area label for this to make it easier to filter out things related local use-case

/area local

**Comment by j-c-berger** [comment]
@elsony, Hey Elson, do you need ID support for this issue? If so, let me know what you need! :)

**Comment by elsony** [comment]
@j-c-berger This is the public repo for odo. Let's take offline on any of the Codewind project specific questions outside of this repo.

**Comment by girishramnani** [comment]
closing this epic as we have decided to discontinue support for docker (local) support
