### ISSUE TITLE
describe operator backed services

### ISSUE THREAD

**Issue by kadel** [openshift/odo#2615]
## User Story
As a user, I want to get detailed information about operator backed service before I create it 

## Acceptance Criteria 
- [ ] `odo catalog describe service <name>` should provide detailed information about the service from OperatorHub.
- [ ] `odo catalog describe service <name> -o json` should provide detailed information about the service from OperatorHub in json format

Same AC moved from #2785 
- [ ] `odo catalog describe service <service-mame>` - should include all available parameters, that can be used in `odo service create` command.
-  [ ] `odo catalog describe service <service-mame> -o json` - should include all available parameters, that can be used in `odo service create` command in json format, so it can be programmatically parsed and proper `odo service create` command can be generated

## Links 
- Feature Request: https://github.com/openshift/odo/issues/2480
- Related issue: 

/kind user-story
/area catalog
/area service-operators

**Comment by kadel** [comment]
I would suggest addressing  #2613 (Instantiate service through Operator)  first.
When #2613 is implemented it will create nice MVP, that can already be used by odo users (list what can be installed `odo catalog list services` and install it using `odo service create`)

**Comment by dharmit** [comment]
/remove-lifecycle stale
/lifecycle frozen

Still very relevant.

**Comment by dharmit** [comment]
@girishramnani Does this issue still need any more information? I see everything around this being discussed on #4240.

**Comment by girishramnani** [comment]
alot has changed since creation on this issue - my idea here is to create the proposal for #4240 and then that would change alot of things like this issues and some other like this and then work in each. ( dont worry this wont take long )

**Comment by girishramnani** [comment]
## Current scoped work

We were able to figure out how a `non-admin` user was able to still see the form. Its based on `spec.customresourcedefinitions` present in the ClusterServiceVersion.
Now this CRD def is different then whats provided by the `CustomResourceDefinition` ( it has less information ) but as we dont have access to `CustomResourceDefinition` kind as a normal user we cannot use it, so instead we use `ClusterServiceVersion`'s crd def.

This is how one of the `customresourcedefinition` looks like ( Kafka from strimzi )
```
[
    {
        "description": "Kafka version",
        "displayName": "Version",
        "path": "kafka.version",
        "x-descriptors": [
            "urn:alm:descriptor:com.tectonic.ui:text"
        ]
    },
    {
        "description": "The desired number of Kafka brokers.",
        "displayName": "Kafka Brokers",
        "path": "kafka.replicas",
        "x-descriptors": [
            "urn:alm:descriptor:com.tectonic.ui:podCount"
        ]
    },
    {
        "description": "The type of storage used by Kafka brokers",
        "displayName": "Kafka storage",
        "path": "kafka.storage.type",
        "x-descriptors": [
            "urn:alm:descriptor:com.tectonic.ui:select:ephemeral",
            "urn:alm:descriptor:com.tectonic.ui:select:persistent-claim",
            "urn:alm:descriptor:com.tectonic.ui:select:jbod"
        ]
    },
    {
        "description": "Limits describes the minimum/maximum amount of compute resources required/allowed",
        "displayName": "Kafka Resource Requirements",
        "path": "kafka.resources",
        "x-descriptors": [
            "urn:alm:descriptor:com.tectonic.ui:resourceRequirements"
        ]
    },
    {
        "description": "The desired number of Zookeeper nodes.",
        "displayName": "Zookeeper Nodes",
        "path": "zookeeper.replicas",
        "x-descriptors": [
            "urn:alm:descriptor:com.tectonic.ui:podCount"
        ]
    },
    {
        "description": "The type of storage used by Zookeeper nodes",
        "displayName": "Zookeeper storage",
        "path": "zookeeper.storage.type",
        "x-descriptors": [
            "urn:alm:descriptor:com.tectonic.ui:select:ephemeral",  
            "urn:alm:descriptor:com.tectonic.ui:select:persistent-claim",
            "urn:alm:descriptor:com.tectonic.ui:select:jbod"
        ]
    },
    {
        "description": "Limits describes the minimum/maximum amount of compute resources required/allowed",
        "displayName": "Zookeeper Resource Requirements",
        "path": "zookeeper.resources",
        "x-descriptors": [
            "urn:alm:descriptor:com.tectonic.ui:resourceRequirements"
        ]
    }
]
```

As first step we would show this value as is when someone asks for json output for `Kafka` from `strimzi`.

 - `odo catalog service describe strimzi-cluster-operator.v0.21.1/Kafka` would show the above json


Similarly the output for human readable output would be -

## TODO

**Comment by girishramnani** [comment]
@dgolovin Please validate the json output part - we might add `parameters : [ ...` to just keep the top level of the json a map but the output structure would stay the same.

**Comment by girishramnani** [comment]
Also do we wanna do autocomplete? we would need to do some caching for a usable autocomplete as the api call would be slow.

**Comment by kadel** [comment]
> Or Maybe consider a non tablular approach instead?

I would go with tabular.




> Also maybe we can sort the fields using the `fieldpath`? so it would look like

I would keep the original ordering. It looks like it follows some logical ordering.



> Also do we wanna do autocomplete? we would need to do some caching for a usable autocomplete as the api call would be slow.

We can check  autocomplete later. Not a high priority now.

**Comment by girishramnani** [comment]
I had a question how to distinguish if the user is asking for service catalog service or an operator.
Should I assume if its of the format `<operator>/<CR>` i.e. `strimzi-cluster-operator.v0.21.1/Kafka` then its operator CR?

**Comment by girishramnani** [comment]
Also if a user provide just `odo catalog describe service <operator-name>` then should I show all `CRs` under it?
If so then we need to find a better way to distinguish if a user is asking for operators backed services or service catalog services

**Comment by kadel** [comment]
> I had a question how to distinguish if the user is asking for service catalog service or an operator.
> Should I assume if its of the format `<operator>/<CR>` i.e. `strimzi-cluster-operator.v0.21.1/Kafka` then its operator CR?
> @kadel

yes





> Also if a user provide just `odo catalog describe service <operator-name>` then should I show all `CRs` under it?
> If so then we need to find a better way to distinguish if a user is asking for operators backed services or service catalog services

if it is operator based service it should always be specified as operator/cr
