### ISSUE TITLE
Add significantly more documentation on Devfile v2 / website update / Kubernetes integration

### ISSUE THREAD

**Issue by cdrage** [openshift/odo#2725]
/kind documentation

## What mistake did you find / what is missing in the documentation?

Although we are in the middle of implementing Devfile, we should have ample documentation on how to get started with Devfile as well as a general "hello world" example.

More is outlined in the Google doc below:

Update / add comments here!

https://docs.google.com/document/d/1k-T4tlcb2Lx21hyhJYWormga5a-ImfmL_Phtnf6JSgA/edit?ts=5ef50de3

## What is the relevance of it?

Needed more information on Devfile documentation

## TODO LIST

TODO:

- [x] Added documentation on v2
- [x] Added documentation on how to edit the yaml and update build / run / etc sections
- [x] Documentation downstream vs upstream (openshift docs vs devfile site)
- [x] Have odo.dev have ONLY devfile not S2I when we do the separate releases (devfile alpha vs s2i openshift productized release)

**Comment by cdrage** [comment]
TODO:

- [ ] Added documentation on v2
- [ ] Added documentation on how to edit the yaml and update build / run / etc sections

**Comment by elsony** [comment]
@cdrage  Does this item includes the update of the CLI reference doc: https://docs.openshift.com/container-platform/4.5/cli_reference/developer_cli_odo/odo-cli-reference.html ?

**Comment by cdrage** [comment]
@elsony Ideally we would have all documentation "here" and then sync "downstream" to the OpenShift docs. But yes, we would like to update that document.

**Comment by elsony** [comment]
@cdrage For the CLI reference https://odo.dev/docs/odo-cli-reference, can we add:
1. the usage of the `--starter` flag for starter project creation to the reference on the create command https://odo.dev/docs/odo-cli-reference/#create?
2. the `odo test` command reference (https://github.com/openshift/odo/issues/3284) that we have added in Sprint 187?

**Comment by cdrage** [comment]
> @cdrage For the CLI reference https://odo.dev/docs/odo-cli-reference, can we add:
> 
> 1. the usage of the `--starter` flag for starter project creation to the reference on the create command https://odo.dev/docs/odo-cli-reference/#create?

I agree that we should add this to the CLI reference. 

> 2. the `odo test` command reference (#3284) that we have added in Sprint 187?

I agree too. If you can open up a PR on this that'd be great.

> 
> Also, for the install page https://odo.dev/docs/installing-odo/, can we add a copy button to copy the install commands?

Unfortunately the way we have it right now (converting from markdown to asciidoc), I'd be unable to add a copy button :(. But I'll look into it!
