### ISSUE TITLE
Update all materials (readme, help messages, docs) to focus more on Kubernetes

### ISSUE THREAD

**Issue by sspeiche** [openshift/odo#2777]
`odo` is evolving past its 1.0 scope to be rooted on Kubernetes and also support OpenShift. Therefore we need to update various messaging to improve on this.

There are many places where the old tag line "OpenShift Do" exists.

Proposed changes from:
   `OpenShift Do - Fast, iterative OpenShift development`
to:
   `odo - Fast, iterative Developer-focused CLI for Kubernetes & OpenShift`

These changes should occur on:
- [ ] Homepage
- [x] [README](https://issues.redhat.com/browse/RHDEVDOCS-1834)
- [ ] `odo -?`
- [x] [Documentation](https://issues.redhat.com/browse/RHDEVDOCS-1835)
- [x] ~~Blogs~~
- [x] odo.dev (https://github.com/openshift/odo/issues/2725)
- [ ] https://github.com/openshift/odo/issues/3749

I'd strongly just refer to it as `odo`, which I don't think we need a proper noun version "Odo" that starts sentences.  If you read the man page for `sh`, it never calls it "Sh". The tool name is `odo`.

**Comment by girishramnani** [comment]
@Preeticp if you can please break down this epic into small parts and attach them here so we can have an itemised view on the epic's progress.

**Comment by Preeticp** [comment]
@girishramnani here's the doc issue that tracks this Epic: https://issues.redhat.com/browse/RHDEVDOCS-1823, do let us know if it needs any modifications.

**Comment by girishramnani** [comment]
Actually I was hoping for a list of issues (assuming this cannot be done in a single sprint)

**Comment by Preeticp** [comment]
Updated description with links to sub-tasks in the documentation epic. Also added an entry for Blogs in the checklist, please delete it if this is not within the scope of this issue.

**Comment by girishramnani** [comment]
@Preeticp can we please check off the acceptance criteria's that have been done?

**Comment by Preeticp** [comment]
From the docs team side, this has been taken care of in the Readme and the Documentation. I have checked them off @girishramnani

**Comment by sspeiche** [comment]
What work is left in blogs? I have been reviewing new blog posts from developers.redhat.com/blog and updated the internal FAQ on naming usage.

**Comment by Preeticp** [comment]
Struck down the Blogs part in the list, post our discussion. If the odo part, such as man pages and code have also been updated to odo, then we can close this issue.

**Comment by prietyc123** [comment]
@boczkowska @girishramnani Is this the final doc related issues list or we are expecting to consider some more?

**Comment by cdrage** [comment]
With the exception of https://github.com/openshift/odo/issues/3749 I have addressed all above concerns with regards to Kubernetes references on our home page.

As discussed with DV, we went through (most) of the documentation with regards to OpenShift references and ensured that it says Kubernetes (first) and then OpenShift.

**Comment by cdrage** [comment]
https://github.com/openshift/odo/issues/3749 has been merged and has also been merged to add the document to the website.

We can safely close this issue now!
