### ISSUE TITLE
Support Devfile 2.0 format on devfile components

### ISSUE THREAD

**Issue by elsony** [openshift/odo#2933]
Add support to devfile 2.0 format when reading the devfile.yaml. Details of the devfile 2.0 support can be found in https://github.com/che-incubator/devworkspace-api/issues/15.

This item includes:
MVP:
- [x] Devfile 2.0 parser (#2918)
- [x] devfile v2 support for odo push (k8s and OpenShift) (#3140)
- [x] Specify the source mapping path for component containers (#2935) 
- [x] Container initialization (#2936)
- [x] Specific working directory in container (#2937)
- [x] Command group (application lifecycle) (#2938)
- [x] Renaming dockerimage component type (#2939)

MVP +:
- [x] Support composite commands (#3338)
- [x] Add parent support (devfile 2.0) to devfile (#2919 )
- [x] Allow the size of a component's volume to be specified in a Devfile (#3407)
- [x] Allow volumes to be shared across components (#3407)
- [x] Environment variables for a specific command (#3406)

/area devfile

**Comment by girishramnani** [comment]
epics shouldn't be assigned `required-for-v2` labels

**Comment by kadel** [comment]
/close
all done
