### ISSUE TITLE
odo link should store link information in devfile

### ISSUE THREAD

**Issue by kadel** [openshift/odo#4208]
/kind user-story

## User Story
As a developer working with odo,  I want to be able to easily share link connections to a service or to another odo component, with my team so they can start application with the service in the same way as me. 

## Acceptance Criteria 
- [x] `odo link` should store link description in devfile. For example, if ServiceBindingOperator is used `ServiceBinding` CR will be stored in devfile as `kubernetes` component (#4819).
- [x] `odo unlink` should remove appropriate `kubernetes` component from devfile (deletion from the cluster will happen during `odo push`) (#4819)
- [ ] `odo link` should work when linking to an Operator backed service that’s not pushed yet. But it shouldn’t work when trying to link to another component that’s not pushed yet.
- [ ] `odo describe` should list all links for the current component together with the status. The status will be similar to URL statuses as the link can be present locally but missing on the cluster, or present on the cluster and missing locally, or present in both places. (#3734). Also the JSON output (`odo describe -o json`) for this.

## Links 
- Feature Request: 
- Related issue: 

/kind user-story

**Comment by dharmit** [comment]
> * [ ] `odo unlink` should remove appropriate `kubernetes` component from devfile (deletion from the cluster will happen during `odo push`)

What I can't wrap my head around is that how will odo know that some resource on the cluster (here a `ServiceBinding`) needs to be deleted. Here's the flow we're looking for:
1. `odo link` will store the manifest of a `ServiceBinding` in devfile.yaml
2. `odo push` will create the `ServiceBinding` on the cluster if one doesn't exist already.
3. `odo unlink` will remove the manifest of the `ServiceBinding` from devfile.yaml
4. `odo push` should delete the `ServiceBinding` from the devfile.yaml

Now, between step 3 & 4, how is odo going to know that it has to delete something from the cluster? Should we store some information about the link created in step 1 in the `.odo/env/env.yaml` file?

**Comment by dharmit** [comment]
#4777 will go in soon. It'll address the long-pending feature that we had working with s2i components. @feloy please also consider that `odo link` now works with both an Operator backed service and another odo component.

**Comment by feloy** [comment]
When creating a link, do we want to target only services/components deployed in the cluster, or should we also be able to create a link to service in a "Not Pushed" state?

Note that it won't be possible to link to a non-deployed component, as we don't have access to the devfile in this case (the linked component is from another devfile)

**Comment by dharmit** [comment]
IMO, for 2.3, we should focus on the services and components that already exist on the cluster. My reasoning for this is to keep it simple and working with not many cases and edge cases to think of at the moment. So, yes, it's only because we're nearing the end of 2.3 milestone.

Otherwise, being able to link to "not pushed" services/components seems like an interesting use case.

WDYT @kadel?

**Comment by feloy** [comment]
A question concerning the OwnerReferences.

With this PR, the links are saved as Inlined Kubernetes resources, as the Operator backed services.

To keep owner references on the ServiceBinding, I will make `odo push` set ownerReferences on Inlined Kubernetes resources, at least the ServiceBinding ones.

Do we want to set owner References on Operator backed services too (I cannot see them for the moment), or should `odo push` set these references only on the ServiceBinding resources?

**Comment by dharmit** [comment]
I think it should set it for all Operator backed services, or rather, all Kubernetes inlined resources in devfile. @kadel mentioned that outer loop tools would use Kubernetes inlined resources at some point. So if this makes sense from outer loop perspective or not, that's what I am not sure of. But from odo perspective, setting `ownerReferences` to all Kubernetes inlined resources sounds like the way to go to me.

**Comment by kadel** [comment]
> When creating a link, do we want to target only services/components deployed in the cluster, or should we also be able to create a link to service in a "Not Pushed" state?

Yes,  we definitely want this https://github.com/openshift/odo/issues/4760 
It is almost a must-have. It would be quite annoying if users would have to run `odo service create` then `odo push` and wait for service to start, only then could they run `odo link` and `odo push` again, and wait again. 

> Do we want to set owner References on Operator backed services too (I cannot see them for the moment), or should `odo push` set these references only on the ServiceBinding resources?

Yes, we can set it on operator-backed services as well. It will solve this issue https://github.com/openshift/odo/issues/4750

Just keep in mind that this might change in the future. Once we start with the outerloop. The "main" `Deployment` that we currently tie everything to, might not exist. Currently, this `Deployment` is only for inner loop. For outer loop  there will be completely different `Deployment` or there might be something else, like `StatefullSet` or Knative service ... .
