### ISSUE TITLE
allow linking using ServiceBinding without ServiceBindingOperator

### ISSUE THREAD

**Issue by kadel** [openshift/odo#4543]
## Goal
For developer to be able to link components and applications without the service binding operator having to be installed (self-service)

## Acceptance Criteria
- [ ] `odo link <service-name>` should work without having Service Binding Operator installed
- [ ] `odo link <component-name>` should work without having Service Binding Operator installed
- [ ] `odo unlink` should work correctly with links that don't use Service Binding Operator
- [ ] `odo describe` should work correctly (displaying links, evns etc...) with links that don't use Service Binding Operator

## Dependencies
~~Need access to the service binding library in order for this work to begin.~~

##  JIRA Epic Tracking
[ODO-59](https://issues.redhat.com/browse/ODO-59)

**Comment by kadel** [comment]
I've done a small POC based on the changes introduced in https://github.com/redhat-developer/service-binding-operator/pull/919

Thanks to the changes in that PR it is possible to easily create binding without an operator.
https://github.com/kadel/odo/blob/f87c8aa3acc3908d093fa5ef8d3f57cd27036295/pkg/odo/cli/component/common_link.go#L322-L334

```go
mgr, _ := ctrl.NewManager(ctrl.GetConfigOrDie(), ctrl.Options{
	Scheme: runtime.NewScheme(),
})
out, _ := json.MarshalIndent(o.serviceBinding, " ", " ")
fmt.Printf("%s\n", string(out))
pipeline := builder.DefaultBuilder.WithContextProvider(context.Provider(o.KClient.DynamicClient, context.ResourceLookup(mgr.GetRESTMapper()))).Build()
repeat, err := pipeline.Process(o.serviceBinding)
// you can read secret name from the passed service binding... Status.Secret
// for unbind the passed service binding instance must have deletetion timestamp set
out2, _ := json.MarshalIndent(o.serviceBinding, " ", " ")
fmt.Printf("%s\n", string(out2))
fmt.Println(repeat)
fmt.Println(err)
```

**Comment by girishramnani** [comment]
there is a complexity in writing tests ( we install SBO cluster wide so we cannot write test for testing this feature) so we would expose an env variable to skip the SBO's usage. maybe `SKIP_SBO`?

**Comment by girishramnani** [comment]
We can skip SBO installation on minikube and so all tests would use this feature

**Comment by dharmit** [comment]
- When using the Operator, it provides more features than using it as library
- Other tools can understand Service Binding resources
  - ODC understands and draws it on the UI.
- Without Operator, you wouldn't be creating a Binding resource on the cluster but injecting the env vars directly into the Deployment.
- odo wants to do it without the Operator as well because installing Operator is admin task and would compel a user to install Operator first.

**Comment by kadel** [comment]
This was solved only partially.
There is still one big problem https://github.com/openshift/odo/issues/4965
