### ISSUE TITLE
Link via ServiceBindingRequest, part 2

### ISSUE THREAD

**Issue by serenamarie125** [openshift/odo#4590]
## Description
As a developer, I would like to be able to easily inject my source component with the config/secrets/envvars needed to invoke a backing application, so I can focus on may application code instead of configuring application connections.

## Acceptance criteria
* User can issue link command and then push changes, when pushed it will be determined that the components are compatible for `ServiceRequestBinding` and perform the function.
* User can list linked components
* User can unlink, or remove link.

## User Stories

- [x] odo link should store link information in devfile #4208
- [x] Suport linking devfile component with another component (https://github.com/openshift/odo/issues/3423)

## Good to have 

- [x] Disallow self linking of a component (https://github.com/openshift/odo/issues/1052)
- [x] Add linked component/service information in odo describe for devfile component and operator services (https://github.com/openshift/odo/issues/3734)

## JIRA Epic Tracking
[ODO-47]( https://issues.redhat.com/browse/ODO-47)

**Comment by serenamarie125** [comment]
@dharmit @kadel  could you add story points?  Thank you

**Comment by dharmit** [comment]
All User Stories covered including those in "Good to Have".

/close
