### ISSUE TITLE
Instantiate and manage services through Operator, part 2

### ISSUE THREAD

**Issue by serenamarie125** [openshift/odo#4591]
## User Story
As a user, I want to create a new instance of my database or another service managed by operators So that I can use it (link it) with my application

## Acceptance Criteria 
- [ ] `odo service create -o json` create a new instance of an operator in my project, and output information about the created operator in JSON format (the output should have the same info as `odo service describe <newly created service> -o json`) (#2784)
- [ ] `odo service describe <service name>` should print detailed information about service that was created (for example if is it running or not, how many instances it has, what parameters were used to create this service)
- [ ] `odo service describe <service name> -o json` should print detailed information about service that was created (for example if is it running or not, how many instances it has, what parameters were used to create this service) in JSON format (#2784)
- [ ] `odo catalog describe service <name>` & `odo catalog describe service <name> -o json` should provide detailed information about the service from OperatorHub. (#2615)

### good to have:
- [ ] `odo service create` should allow user to interactively create operator backed services (#2799)
- [ ] User should not be required to provide or write any CR definitions or YAML. It should be possible to provide additional arguments for operator via the command line (as arguments to `odo service create` command) https://github.com/openshift/odo/issues/2785

## Links 
- Feature Request: https://github.com/openshift/odo/issues/2462
- Feature Request: https://github.com/openshift/odo/issues/2161

/area service-operators
/area service
/kind feature

**Comment by serenamarie125** [comment]
@kadel @dharmit please update with story points, thanks!

**Comment by dharmit** [comment]
>  `odo service describe <service name>` should print detailed information about service that was created (for example if is it running or not, how many instances it has, what parameters were used to create this service)

This command is applicable only for a service that's already created using `odo service create` (maybe even pushed to the cluster using `odo push`.) So we already have the spec of the service. We only need to print the spec in a pretty way.

**Comment by dharmit** [comment]
@serenamarie125 pointed it to 4 and added one more item to acceptance criteria - #4160.

**Comment by dharmit** [comment]
Moved #2785 from "good to have" to "Acceptance Criteria' since it is immediate next step after `odo catalog describe service`.
