### ISSUE TITLE
Test `odo link` extensively for 2.3 release

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#4801]
### Goal
`odo link` has added a bunch of capabilities and fixed some issues. This issue tracks all the scenarios we should check before 2.3 release and make sure they are working well.

### Acceptance Criteria
A component means devfile based component
#### Must haves
- [x] `odo link` a component with an Operator backed service (https://github.com/openshift/odo/issues/4801#issuecomment-872022431)
- [x] `odo link` a component with another component (https://github.com/openshift/odo/issues/4801#issuecomment-872022431)
- [x] `odo link --name` a component with an Operator backed service and check if SBR (`kubectl get sbr`) gets created with the provided name (https://github.com/openshift/odo/issues/4801#issuecomment-872022431)
- [x] `odo link --name` a component with another odo component and check if SBR (`kubectl get sbr`) gets created with the provided name (https://github.com/openshift/odo/issues/4801#issuecomment-872022431)
- [x] `odo link --name --bindAsFiles` and see if values are injected as files instead of environment variables (https://github.com/openshift/odo/issues/4801#issuecomment-872022431)
- [x] `odo link` a component with more than one Operator backed service or component (https://github.com/openshift/odo/issues/4801#issuecomment-872022431)
- [x] `odo link --app`

#### Stretch
- [x] Link component A with component B; link component B with an Operator backed service. Ideally, do this with an end-to-end microservices application. (https://github.com/openshift/odo/issues/4801#issuecomment-872022431)
- [x] `odo describe` should list all the services linked to the component. See https://github.com/openshift/odo/pull/4819#issuecomment-871359275
- [ ] Delete a linked service/component and check what happens. (https://github.com/openshift/odo/issues/4801#issuecomment-872169765)

**Comment by valaparthvi** [comment]
Tested this issue against @feloy's PR #4819 and all the ticked acceptance criteria work well.

**Comment by valaparthvi** [comment]
Testing AC - Deleting a linked service/component

Steps to reproduce - 
1. Create a component and push it.
2. Create another component or a service and push it.
3. Create a link to the other component/service and push it.
4. Delete the component/service created in step 2.
5. Try un-linking the deleted component/service from step 4.

Got - 
```
 ✗  couldn't find service named XXX. Refer "odo service list" to see list of running services
```

Want -
Not sure what could be the expected outcome here.

**Comment by feloy** [comment]
> Testing AC - Deleting a linked service/component
> 
> Steps to reproduce -
> 
> 1. Create a component and push it.
> 2. Create another component or a service and push it.
> 3. Create a link to the other component/service and push it.
> 4. Delete the component/service created in step 2.
> 5. Try un-linking the deleted component/service from step 4.
> 
> Got -
> 
> ```
>  ✗  couldn't find service named XXX. Refer "odo service list" to see list of running services
> 
>  ✗  couldn't find component named XXX. Refer "odo list" to see list of running components
> ```
> 
> Want -
> Not sure what could be the expected outcome here. It doesn't necessarily block anything because the user can still delete the linked service via web console.

Good catch.

Should `odo` forbid to delete a service/component when a link references it, or should `odo` delete the link when deleting the service/component?

**Comment by dharmit** [comment]
> Should `odo` forbid to delete a service/component when a link references it, or should `odo` delete the link when deleting the service/component?

IMO, odo should forbid deletion of a service/component that's linked to another component. But that should not be the case if the component initiated the link (step 1 in https://github.com/openshift/odo/issues/4801#issuecomment-872169765). For such components, odo should delete the binding (which it already does, thanks for `ownerReferences`.)

@valaparthvi can you open a bug to track this?

**Comment by valaparthvi** [comment]
> @valaparthvi can you open a bug to track this?

https://github.com/openshift/odo/issues/4871

**Comment by valaparthvi** [comment]
@dharmit IMO with @feloy's #4866 PR, `odo link` works well and is ready for a release. I cannot think of any more scenarios to test.

**Comment by dharmit** [comment]
@valaparthvi I'm good by marking it Done.
