### ISSUE TITLE
IBM Cloud - Research options to create and use VMs

### ISSUE THREAD

**Issue by rnapoles-rh** [openshift/odo#4988]
/kind task

## Task
As a QE engineer I want to to be able to create and use VMs in the IBM Cloud So that I can use them to run automated tests

## Acceptance Criteria 
- [x] Identify the options and process to create VMs in the IBM Cloud
- [x] POC to create Linux VM
- [ ] POC to create Windows VM
- [x] Get licenses for Windows base VMs

## Links 
- Related Epic (mandatory): 
#4897

**Comment by rnapoles-rh** [comment]
Linux VM created in the IBM Cloud:
![image](https://user-images.githubusercontent.com/72166315/132500336-c06c21f5-418d-4cf5-9b3b-36573e9c0588.png)
Setting up IBM Cloud prerequisites

**Comment by rnapoles-rh** [comment]
can not ssh to Linux Vm hosted in the IBM cloud, debugging.
For Windows VM I was able to create a storage bucket and upload a windows 10 VM, but not shown when trying to create a custom VM

**Comment by rnapoles-rh** [comment]
We

> can not ssh to Linux Vm hosted in the IBM cloud, debugging. For Windows VM I was able to create a storage bucket and upload a windows 10 VM, but not shown when trying to create a custom VM

By using ssh-key we can ssh to the Linux VM

**Comment by rnapoles-rh** [comment]
We will be using Windows server VM in the IBM Cloud, VM is fully configured now in the Developer QE org.
