### ISSUE TITLE
Set active component/application when user in directory (new odo workflow)

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/odo#600]
**Detailed description in** https://docs.google.com/document/d/1RKva9lvIR6dLmDm2tlqmp8V4nFjlrXdulOQ4FSmLkr8

Sub Issues :

- [x]  new odo workflow: create `odo config` and `odo preference` commands #1365 
- [x] new odo workflow: `odo create` and `odo push` to use local config #1366 
- [x] new odo workflow: handle env in odo config #1390
- [x] new odo workflow: odo watch #1419
- [x] new odo workflow: odo url #1389
- [ ] new odo workflow: odo storage #1388
- [x] new odo workflow: odo config --context #1371 
- [x] new odo workflow: odo push --context #1373 
- [x] new odo workflow: odo component create --context #1372
- [x] new odo workflow: odo watch --context #1419
- [x] new odo workflow: odo component create and odo config behaviour #1447
- [ ] everything labels [new workflow](https://github.com/openshift/odo/issues?q=is%3Aissue+is%3Aopen+label%3A"new+workflow")

---

One thing I noted is that when a user is working on multiple components, or even on different applications, some actions might happen in the wrong component application because switching components/applications is not a natural action for the user, but rather an `odo` requirement.

I was working on this scenario:

```bash
cd frontend
odo create wildfly frontend --binary target/ROOT.war
cd ../backend
odo create nodejs backend
cd ../frontend
odo push
# HERE I GOT AN ERROR BECAUSE I PUSHED THE BINARY WAR TO THE NODEJS COMPONENT
```

Obviously, it was my mistake, but I think this is a natural mistake.

I'm thinking we might need to introduce a feature in odo that monitors the directory we're in (as part of the terminal integration) and depending on our directory set the active application and active component, so I can safely "cd" back and forth and be sure I'm always in the right context.

There's a tool I use, called [direnv](https://direnv.net/) that does basically this. In our case, I don't think the files should be placed in the working directory, but the configuration should be in the `odo config` file.

Something similar to this (don't look into format):
```
- dir: 
     path: /home/jmorales/backend
     app: MYAPP
     component: backend
- dir: 
     path: /home/jmorales/frontend
     app: MYAPP
     component: frontend
```

Then if I cd to either of those directories, odo will set the correct app and component so I can safely push. I can always explicitly use `--component other-component --application other-app` to push to a different app.

If we go this route, things that need to be thought are:
- File format
- When to delete a configuration entry
- When to create a configuration entry
- How to inform the user if the current application changes (when I `cd` into a configured directory?
- How to inform the user if the current component changes (when I `cd` into a configured directory?
- Is the entry specific to the k8s context?
- How to keep the active application as we do now? Does it make sense if we're not in a source directory?
- How to keep the current component as we do now? Does it make sense if we're not in a source directory?

**Comment by jorgemoralespou** [comment]
There's (at least) 3 type of Java applications directory structure (that I have identified), and we need to make sure what level of support are we going to provide to each with this functionality. These typologies are identified based on my knowledge of maven. I guess that gradle will be similar.

1. single git repository per component
1. single git repository with an aggregator (multi-module) project that generates only one deployable artefact
1. single git repository with an aggregated project (only common parent pom) that generates multiple deployable artefacts

The first option is directly supported, and it's what's recommended on the inmutable containerized world.
The other two options, in order to make them work on OpenShift's S2I someone needs to know the caveats.

If the build is happening in the container, you need to provide the root directory of the repository, as the pom.xml file in that directory will provide the module information and/or dependencies information.

One might need to specify the following properties (for the openjdk-s2i image):
- ARTIFACT_DIR: location of where the artifact will be available once the build process has finished
- JAVA_APP_JAR: the name of the generated artifact to use

When building locally, one will only need to specify the location of the artifact binary `--binary`.

The problem comes with the 3rd option, as when this issue is implemented, the root folder could be the root for 2 different components. We need to think if we want to support this scenario, and if we do, how we can support this scenario.

The first 2 scenarios, as only produce one artefact, would only generate one single component, which means that when you directly `cd` into that directory, `odo` could have everything it needs to create/push to the component, and obviously, to set it as the active component.

**Comment by jorgemoralespou** [comment]
@kadel, it wouldn't work if you build in the component, as when you push it would only push that directory and not the root one, which has the pom.xml that is referenced in the subproj1/pom.xml as parent.
This is the case referenced in https://github.com/redhat-developer/odo/issues/1014

In order to work, you need to push from `myproj`.

**Comment by kadel** [comment]
If this is not that common, It might be better to say that this is a structure that odo doesn't support. As we discussed this before, odo can't support everything.

**Comment by jorgemoralespou** [comment]
@kadel, agree. And for the time being I would think this is ok. This is definitely not a pattern followed by  greenfield applications. Currently it can be found on many repositories in Github in many of the "quickstarts" for our projects (fuse, wildfly,...).
We should definitely document that it's only supported if you build locally and how it could be supported, and limitations, as once a project like this will be used for a component, it could not be easily used for other component if the .odo configuration files writes information on the component.

**Comment by cdrage** [comment]
Blocked by #1092 at the moment

**Comment by girishramnani** [comment]
what I think we can do here is that, once odo-config PR https://github.com/redhat-developer/odo/pull/1168, we essentially can change the workflow to essentially having two configs in the `LocalConfig` 
- `CurrentApplication`
- `CurrentComponent`

We dont need to keep a list of directories mapping to the current components and applications as the local config folder already is like a beacon to the current directory. But this confines us to 1 odo config having only 1 current component in 1 directory. 
So if we want to have multiple components in one directory then we have to consider a list in the local odo config ( but the directories should be kept relative to the root folder where the odo-config.yaml resides)

**Comment by girishramnani** [comment]
we need to break down this issue into smaller chunk

**Comment by kadel** [comment]
First part:
 - When a component is created, save configuration flags to the local file (--env, --mem, --cpu, --application, component type (builder image), --port)
 - When `odo push` is called push current directory into component specified in local config (.`.odo/config.yaml`)

**Comment by girishramnani** [comment]
for now we would be considering only 1 component per directory @kadel ?

**Comment by kadel** [comment]
> for now we would be considering only 1 component per directory @kadel ?

`.odo` directory = 1 component

**Comment by kadel** [comment]
closing this issue, most of this is done. What is left is tracked in the issues marked with  label [new workflow](https://github.com/openshift/odo/issues?q=is%3Aissue+is%3Aopen+label%3A"new+workflow")
