### ISSUE TITLE
Full support for Java

### ISSUE THREAD

**Issue by kadel** [openshift/odo#807]
Make sure that odo works with standard Java and related (Wildfly, Spring ...) builder images.

related issues:
 - [x] wildfly component gets broken after storage is added #445
 - [x] ~~Clarify whether Java is a supported language #686~~
 - [x] Create Java example and use it in our test suite kind/testing #777
 - [x] ~~supervisord's commands to run the java s2i's application are not correct #707~~
 - [x]  Autodetect path for assemble and run scripts #869
 - [x] Doc - Add a section to explain how to install a java, spring boot application #839

**Comment by dharmit** [comment]
@kadel I removed the `epic` label and added `documentation` since it's only the docs that need to be added for this. But I'm guessing that's wrong since we have a dedicated issue open for the docs part of the epic. WDYT? :thinking:

**Comment by dharmit** [comment]
Last remaining issue from the issue description has been closed with an example of Java made available in the docs. Hence marking this closed.

/close
