### ISSUE TITLE
Add completions using new Completion architecture

### ISSUE THREAD

**Issue by kadel** [openshift/odo#902]
New completion architecture that uses `posener/complete` was added in
https://github.com/redhat-developer/odo/pull/893

It is nicely documented  https://github.com/redhat-developer/odo/blob/master/docs/completion-architecture.md

Currently it works only for `odo service create`.

TODO:
  - [x] Suggesting for application name `odo app delete`, `odo app describe`, `odo app`, `odo app set` + every command that has `--app` flag #937
  - [x] Suggesting for URL name `odo url delete` #938
  - [x] Suggesting component names `odo delete`, `odo component`, `odo link`, `odo push`, `odo watch`, + every command that has `--compnent`` flag #939
 - [x] Suggesting project names `odo project delete`, + every command that has `--project` flag #940
 - [x]  Suggesting storage names `odo storage delete`, `odo storage mount`, `odo storage unmount` #941
 - [x] Suggesting component type in odo create command #1007
 - [x] autocompletion for `odo link` #1064
 - [x] autocompletion for `odo service create` `-p/--parameters` values #1171
 - (I might be have forget something)

**Comment by metacosm** [comment]
It also works for `odo service delete` actually. And there's a bug I need to fix because right now the commands register their associated completion handlers using their names resulting in collisions.

**Comment by kadel** [comment]
@metacosm Is it possible to start working on adding completion for other commands or it will create too many collisions with your work for #871?

**Comment by metacosm** [comment]
@kadel I think that it should be OK with this new architecture because the files more or less now follow what should happen after #871.

**Comment by mik-dass** [comment]
@kadel I would like to pick this up

**Comment by metacosm** [comment]
Also started working on #903.

**Comment by kadel** [comment]
@mik-dass OK, lets do it one entity at a time. Pick one of the entities:  component, app, project, storage, url and make sure that it suggesting works for it.

**Comment by metacosm** [comment]
@mik-dass let me know if you need help and/or you think the doc could be improved.

**Comment by mik-dass** [comment]
@kadel I would pick component for the start since now component names are very big and pain to delete :) @metacosm Thanks :+1:

**Comment by metacosm** [comment]
@mik-dass note that #904 has changed some things, most notably the fact that you now *need* to register completion handlers *after* the command has been inserted in the command hierarchy, something to remember as if you don't do that, the app will exit on registration once #904 is merged.

**Comment by mik-dass** [comment]
@metacosm Looks like #904 is in. Will have a look at the new changes. Thanks :+1:

**Comment by jorgemoralespou** [comment]
@kadel as previously we had `odo utils completion bash` for completion and the process to install bash completion has completelly changed (see https://github.com/redhat-developer/odo/blob/master/docs/completion-architecture.md#enabling--disabling-completion), we need to properly document this in the main help (currently in help it says `--complete` while in the linked doc says `-complete, but both works) for odo as well as in the main README.md. Completion is one of the most important features for productivity.

Also, is the install process `odo -complete` the final process to install completion? It doesn't look intuitive.

**Comment by kadel** [comment]
> Also, is the install process `odo -complete` the final process to install completion? It doesn't look intuitive.

Yep, I don't like it either. I would prefer to move it back to `odo utils`, we already have the  PS1 (`odo utils terminal`), those two should be together

**Comment by cdrage** [comment]
https://github.com/openshift/odo/issues/1171 has been closed (all tasks completed).

We can close this issue now.
