### ISSUE TITLE
Overhaul of documentation in preparation of demo's / future releases.

### ISSUE THREAD

**Issue by cdrage** [openshift/odo#912]
We should re-vamp the documentation so it's a bit more streamlined. Here are a few TODO's on my list.

I'll label this issue as an EPIC.

- [x] Streamline README.md, reducing the information we currently have.
- [ ] Add more documentation on services
- [ ] Add examples on how to link a service(s) to component(s)
- [x] Examples on how to "import" a database into Odo (MySQL, MariaDB, etc.)

And a few more I'll add in the future..

**Comment by surajnarwade** [comment]
cc @jankleinert

**Comment by jankleinert** [comment]
I'm happy to contribute to this in whatever way is most helpful. I think we also need to talk about the watch command more in the docs.

**Comment by cdrage** [comment]
Closing this as: https://github.com/openshift/odo/issues/862 supersedes this.
